[package]
name = "server"
version = "0.1.0"
authors = ["Antti Salonen <ajsalonen@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.8"
actix = "0.7"
env_logger ="*"
osm-xml = "0.6.*"
geo = "0.10.*"
ds = { path = "../ds" }
rmp-serde = "*"
serde = "*"
rand = "*"
