[package]
name = "ai"
version = "0.1.0"
authors = ["Antti Salonen <ajsalonen@gmail.com>"]
edition = "2018"

[dependencies]
ws = "*"
ds = { path = "../ds" }
serde = "*"
serde_derive = "*"
rmp-serde = "*"
